### ISSUE TITLE
XCFramework & SPM support

### ISSUE THREAD

**Issue by AlexisQapa** [BatchLabs/Batch-iOS-SDK#24]
Hi, Xcode 12 is out with support for binary dependencies and we are looking forward fully migrating to SPM.
Batch is currently the last SDK not compatible. Is this actively worked on ? Do you have any ETA for publishing the sdk as a XCFramework in order to support SPM ?

**Comment by abarisain** [comment]
Hello!

Our plan is to release Batch 1.16 as both a .framework and .xcframework. Moving forward we'll only distribute in the xcframework format once Carthage supports it, as it is the only way to provide a Mac Catalyst build and a arm64 simulator slice for Apple Silicon.

Regarding SPM:
Unfortunately, after testing with the GM, we found out that we cannot support SPM for Xcode 12 for the time being.
Long story short, we're running into the same issue as Firebase is: https://github.com/firebase/firebase-ios-sdk/issues/6472 .
We're discussing whether publishing a swift package but require a ugly hack which devs might forget about and cause problems years down the road, or just wait until Apple fixes Xcode. It's probably gonna be the latter as we do not believe that it's a good user experience at all.

Distributing Batch as a dynamic framework (which isn't planned) wouldn't even work, as it is broken too: https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/10

That said, our supplementary SDK for extensions (BatchExtension) will be released on SPM as it will be buildable from source.

**Comment by abiaad** [comment]
Hello @abarisain,

Do you have any news on 1.16 release date ?

Thx

**Comment by abarisain** [comment]
Hi,

I don't wanna make any promises but it should be there at the end of the month.

Please note that we will not support SPM due to the linked bugs

**Comment by abarisain** [comment]
Unfortunately, while Xcode 12.2 beta 3 fixes the Code Signing issue, the framework is unnecessarily copied into the application, greatly increasing its size for no good reason.

It does build and run though.

**Comment by rakesthedon** [comment]
can't you guys create a seperate beta-branch with SPM support?

**Comment by abarisain** [comment]
1.16 (and Xcode 12.2) is not out yet, so we haven't taken a final decision about this

We _might_ end up releasing on SPM, with conditions.

**Comment by abarisain** [comment]
Hello,

1.16.0 has been released and is distributed as a XCFramework.

You'll find a Package.swift on this repository, allowing the use of SPM.
Please note that we consider SPM support of beta quality: we did not document it on purpose.

The current state of Xcode (12.2 beta 3) is that it properly builds and links with the static XCFramework, but mistakenly includes it in the Frameworks/ directory of the app. This makes the app WAY heavier than it should, and also breaks App Store submission.

You will have to find a workaround to remove Batch from the Frameworks/ directory in your build.

I encourage you to follow this thread: https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/30

**Comment by abarisain** [comment]
Xcode 12.2 RC doesn't fix the issue

**Comment by Ded77** [comment]
The issue seems to be fixed with Xcode 12.5 🎉
https://forums.swift.org/t/swiftpm-binarytarget-dependency-and-code-signing/38953/46

**Comment by abarisain** [comment]
It is! We've tested it and it works fine.

We're waiting for the stable Xcode 12.5 release to officially document this.
