### ISSUE TITLE
Description of parameter willShowSystemForegroundAlert in the method BatchPush.handle

### ISSUE THREAD

**Issue by Damien-B** [BatchLabs/Batch-iOS-SDK#25]
I think there's a slight problem in the description of the following method :
`BatchPush.handle(userNotificationCenter: <#T##UNUserNotificationCenter#>, willPresent: <#T##UNNotification#>, willShowSystemForegroundAlert: <#T##Bool#>)`

The documentation of the parameter `willShowSystemForegroundAlert` is cut, there might be a "not missing" in "to show this notification, or."

> Whether you will tell the framework to show this notification, or. Batch uses this value to adjust its behaviour accordingly for a better user experience.

**Comment by abarisain** [comment]
Hello,

Thanks, we'll fix this.

willShowSystemForegroundAlert represents what's given in the completionHandler.

Return true if you're returning  at least [.alert], false if []

**Comment by abarisain** [comment]
Will be fixed with 1.16, thanks for reporting
