### ISSUE TITLE
Event tracking not woking

### ISSUE THREAD

**Issue by bddq** [BatchLabs/Batch-iOS-SDK#36]
## Summary 
Tracking an event without attributes is not tracking the event.

## Reproduction steps
  1. Install Batch SDK with Swift Package Manager
  2. Start the SDK in didFinishLaunchingWithOptions:
  3. Track an event using `BatchProfile.trackEvent(name: "test_event"))`
  4. Check on online Debug tool that the event is not appearing.

## Logs
No logs are displayed in console.

### SDK Version
v2.0.0
### Installation method
SPM
### Relevant development tools versions
Xcode 15.3

### Working calls
That tests are working (console output) and can be seen in the online Debug tool.
`BatchProfile.trackEvent(name: "test_event", attributes: BatchEventAttributes(builder: { _ in }))`

`BatchProfile.trackEvent(name: "test_event", attributes: BatchEventAttributes(builder: { $0.put("test", forKey: "$label" }))`

## Bug idea
It seems you have the error here: https://github.com/BatchLabs/Batch-iOS-SDK/blob/6ac4230b9d21e1b837316a387ce1621906e58a5e/Sources/Batch/BatchProfile.m#L29C5-L31C6
Because `nil` is not kind of `BatchEventAttributes`, you didn't track the event.

Regards,
Benoit

**Comment by arnaud-roland** [comment]
Hi, 
Thanks for the report, we'll release a patch soon for this.

**Comment by arnaud-roland** [comment]
Hi,
I'm closing this since the new version 2.0.1 has been released. 
Thanks again for your report.
